FROM node:10 AS shit
WORKDIR /app
COPY package-lock.json package.json ./
RUN npm install
COPY babel.config.js .
COPY .eslintrc.js .
COPY webpack.config.server.js .
COPY webpack.config.client.js .
COPY lerna.json .

COPY packages ./packages
RUN npm run prestart
RUN npm run test -- --coverage

FROM yurikrupnik/mussia-static-html
WORKDIR /usr/src/app
COPY --from=shit /app/coverage .
ENV ROOT_PATH lcov-report
CMD npm start
EXPOSE 80
