version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017

  devopment:
    build:
      context: .
      #      target: coverage
      dockerfile: ./Dockerfile.dev
    container_name: devopment

  coverage:
    build:
      context: .
      #      target: coverage
      dockerfile: ./Dockerfile.coverage
    container_name: coverage
    ports:
      - 7002:80
    command: npm start
  #
  #  storybook:
  #    build:
  #      context: .
  #      dockerfile: ./Dockerfile.storybook
  #    container_name: storybook-production
  #    ports:
  #      - 7003:80
  #    command: npm start
  #
  app1:
    build:
      context: .
    #      dockerfile: ./Dockerfile.gateway1
    #      target: gateway1
    container_name: app1
    environment:
      - NODE_ENV_DOCKER=true
    ports:
      - 80:80
    command: npm run start
    depends_on:
      - db

  gateway1:
    build:
      context: .
      dockerfile: ./Dockerfile.gateway1
    #      target: gateway1
    container_name: gateway1
    environment:
      - NODE_ENV_DOCKER=true
    ports:
      - 4100:4100
    command: npm run start
    depends_on:
      - db

  service1:
    build:
      context: .
      dockerfile: ./Dockerfile.service1
    #      target: service1
    container_name: service1
    environment:
      - NODE_ENV_DOCKER=true
      - DATABASE_URL=mongodb://db/service1-db
    ports:
      - 5100:5100
    command: npm run start
    depends_on:
      - db

  webserver1:
    build:
      context: .
      #      target: webserver1
      dockerfile: ./Dockerfile.webserver1
    container_name: webserver1
    environment:
      - NODE_ENV_DOCKER=true
    ports:
      - 6100:6100
    command: npm run start
    depends_on:
      - db

#  dev:
#    build:
#      context: .
#      dockerfile: ./Dockerfile.dev
#    container_name: dev
#    volumes:
#      - ./packages:/app/packages
#    environment:
#      - NODE_ENV_DOCKER=true
#      - DATABASE_URL=mongodb://db/dev-db
#    ports:
##      - 80:80
#      - 4000:4000
#      - 5000:5000
#      - 6000:6000
#    command: npm start
#    depends_on:
#      - db
