FROM node:10 as builder
WORKDIR /app

COPY package-lock.json package.json ./
RUN npm install

COPY babel.config.js .
COPY .eslintrc.js .
COPY webpack.config.server.js .
COPY webpack.config.client.js .
COPY lerna.json .
COPY packages/webserver1 ./packages/webserver1

RUN npx lerna bootstrap
RUN npx lerna run build

FROM node:10-alpine
WORKDIR /usr/src/app
COPY --from=builder /app/packages/webserver1/dist .
RUN npm install --only=production

EXPOSE 80
CMD ["npm", "start"]
