version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017

  devopment:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: devopment
    environment:
      - NODE_ENV_DOCKER=true
      - DATABASE_URL=mongodb://db/service1-db
    ports:
      - 3000:3000
      - 3100:3100
      - 5000:5000
      - 5100:5100
      - 4000:4000
      - 4100:4100
      - 6000:6000
      - 6100:6100
    volumes:
      - ./packages:/app/packages
    command: npm run start
    depends_on:
      - db

#  test-watch:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    environment:
#      - NODE_ENV_DOCKER=true
#      - DATABASE_URL=mongodb://db/service1-db
#    volumes:
#      - ./packages:/app/packages
#    command: npm run test -- --watchAll
