FROM node:10 as builder
WORKDIR /app

COPY package-lock.json package.json ./
RUN npm install

COPY babel.config.js .
COPY .eslintrc.js .
COPY webpack.config.server.js .
COPY webpack.config.client.js .
COPY rollup.config.js .
COPY lerna.json .
COPY packages/components ./packages/components
COPY packages/gateway1 ./packages/gateway1
COPY packages/service1 ./packages/service1
COPY packages ./packages

RUN npx lerna bootstrap

EXPOSE 80
CMD ["npm", "start"]
