version: '3'
services:
  e2e:
    image: yurikrupnik/client-apps_e2e
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: e2e
    environment:
      - DEST_PORT=8000
      - PORT=9000
      - DESTINATION_HOST=http://gateway1
    command: npm run e2e
