version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017

  devopment:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: devopment
    environment:
      - NODE_ENV_DOCKER=true
      - DATABASE_URL=mongodb://db/service1-db
    ports:
      - 3000:3000
      - 4000:4000
      - 5000:5000
      - 5001:5001
#    todo automate volumes
    volumes:
      - ./packages/webserver1/src:/app/packages/webserver1/src
      - ./packages/service1/src:/app/packages/service1/src
      - ./packages/ui/button/src:/app/packages/ui/button/src
      - ./packages/ui/list/src:/app/packages/ui/list/src
      - ./packages/gateway1/src:/app/packages/gateway1/src
    command: npm run start
    depends_on:
      - db

  storybook:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: storybook
    ports:
      - 6001:6001
    volumes:
      - ./packages:/app/packages
    command: npm run storybook
    depends_on:
      - db
