version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

only-deploy-tags: &only-deploy-tags
  filters:
    tags:
      only: /^.*/
    branches:
      ignore: /.*/

only-deploy-master: &only-deploy-master
  filters:
    branches:
      only: master
#    branches:
#      ignore: /.*/

jobs:
  docks:
    <<: *defaults
    steps:
      - checkout
#      - run:
#          name: update-npm
#          command: sudo npm install -g npm@6
#      - restore_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
#      - run:
#          name: install-npm-wee
#          command: npm install
#      - save_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
#          paths:
#            - ./node_modules
#      - run:
#          name: install-packages
#          command: npm run pi
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: build
          command: docker-compose build
#          /
#            && docker-compose push

  checkout:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@6
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: install-packages
          command: npm run pi
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run:
          name: config email
          command: git config --global user.email "krupnik.yuri@gmail.com" /
            && git config --global user.name "yurikrupnik"
      - persist_to_workspace:
          root: ~/repo
          paths:
            .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: eslint
          command: npm run lint
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: test
          command: npm run test -- -- -- --coverage
      - run:
          name: Upload Coverage Results
          command: |
            bash <(curl -s https://codecov.io/bash) \
              -n ${CIRCLE_BUILD_NUM} \
              -t ${CODECOV_TOKEN} \
              -y .codecov.yml \
#               \

  deploy_npm:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@6
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: install-packages
          command: npm run pi
      - run:
          name: build-packages
          command: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run:
          name: config email
          command: git config --global user.email "krupnik.yuri@gmail.com" /
            && git config --global user.name "yurikrupnik"
      - run:
          name: check diff
          command: npx lerna changed
      - run:
          name: check a
          command: npx lerna diff
      - run:
          name: publish
          command: npx lerna publish patch --yes

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - checkout
  deploy:
    jobs:
      - checkout
      - deploy_npm:
          <<: *only-deploy-master
#          requires:
#            - build
#      - docks
#      - deploy_to_npm:
#          <<: *only-deploy-tags
#          <<: *only-deploy-master
#            - build
