version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

only-deploy-tags: &only-deploy-tags
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

jobs:
  docks:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: docker login
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
      - run:
          name: build
          command: docker-compose build
      - run:
          name: push images
          command: docker-compose push

  webserver1:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: docker login
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
      - run:
          name: build
          command: docker-compose build webserver1
      - run:
          name: Start Service and Check That it’s Running
          command: |
            docker run -d --name web1 yurikrupnik/client-apps_webserver1
            docker exec web1 curl --retry 10 --retry-connrefused http://localhost:9000
      - run:
          name: push images
          command: docker-compose pus

  checkout:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@6
#      - restore_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
#      - save_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
#          paths:
#            - ./node_modules
      - run:
          name: install-packages
          command: npm run pi
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run:
          name: config email
          command: git config --global user.email "krupnik.yuri@gmail.com" /
            && git config --global user.name "yurikrupnik"
      - persist_to_workspace:
          root: ~/repo
          paths:
            .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: eslint
          command: npm run lint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: test
          command: npm run test -- -- -- --coverage
      - run:
          name: Upload Coverage Results
          command: |
            bash <(curl -s https://codecov.io/bash) \
              -n ${CIRCLE_BUILD_NUM} \
              -t ${CODECOV_TOKEN} \
              -y .codecov.yml \
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            .
#               \

  test-docks:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: compose
          command: docker-compose up
  deploy_npm:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: status
          command: git status
      - run:
          name: checkout
          command: git checkout master
      - run:
          name: update-npm
          command: sudo npm install -g npm@6
#      - restore_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
#      - save_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
#          paths:

#            - ./node_modules
      - run:
          name: install-packages
          command: npm run pi
      - run:
          name: build-packages
          command: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run:
          name: config email
          command: git config --global user.email $git_EMAIL /
            && git config --global user.name $git_name
      - run:
          name: publish
          command: npx lerna publish patch --yes
      - run:
          name: install after
          command: npm run pi
      - run:
          name: git add
          command: git add .
      - run:
          name: git commit
          command: git commit -am "package-lock.json update"
      - run:
          name: git push
          command: git push origin

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - webserver1
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - checkout
  deploy:
    jobs:
      - docks:
          <<: *only-deploy-tags
      - deploy_npm:
          <<: *only-deploy-tags
